build: update build configuration to enable building `mac-x64` version

diff --git a/.github/workflows/compile-and-test.yml b/.github/workflows/compile-and-test.yml
--- a/.github/workflows/compile-and-test.yml
+++ b/.github/workflows/compile-and-test.yml
@@ -13,7 +13,7 @@ jobs:
       contents: write
       id-token: write
       attestations: write
-    
+
     env:
       NODE_NO_WARNINGS: 1
       PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
@@ -28,6 +28,7 @@ jobs:
           - windows-latest
           - ubuntu-latest
           - macos-latest
+          - macos-15-intel
 
     runs-on: ${{ matrix.os }}
 
@@ -37,14 +38,42 @@ jobs:
         with:
           node-version: ">=23.0.0"
 
-      - run: npm install
+      - name: Install dependencies
+        run: npm install
 
-      - run: npm run compile -- -p never
+      - name: Download "denokv-x86_64-apple-darwin" binary for mac-x64 build
+        if: matrix.os != 'macos-15-intel'
+        run: | 
+          releaseUrl=https://api.github.com/repos/AbdulrhmanGoni/denokv-x86_64-apple-darwin-binary-build/releases/latest
+          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -sSL --retry 3 --retry-delay 3 $releaseUrl -o release.json
 
-      - run: npm run test --if-present
+          # Check release.json exists and is not empty
+          if [ ! -s release.json ]; then
+          echo "Failed to download release info into release.json"
+          exit 1
+          fi
+
+          # Extract the download URL of the first and only asset
+          download_url=$(jq -r '.assets[0].browser_download_url' release.json)
+          if [[ -z "$download_url" ]]; then
+          echo "Failed to parse download_url from release.json"
+          cat release.json
+          exit 1
+          fi
+
+          # Download "deno-kv-napi.darwin-x64.node" asset
+          binaryDist=./node_modules/@deno/kv-darwin-x64/deno-kv-napi.darwin-x64.node
+          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -L --retry 3 --retry-delay 3 -o $binaryDist $download_url
+
+      - name: Build the app
+        run: npm run compile -- -p never
+
+      - name: Run tests (Windows, Mac)
+        run: npm run test --if-present
         if: matrix.os != 'ubuntu-latest'
 
-      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test --if-present
+      - name: Run tests (Linux)
+        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test --if-present
         if: matrix.os == 'ubuntu-latest'
 
       - uses: actions/attest-build-provenance@v2
